/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M11
 * Generated at: 2016-11-10 09:16:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_html extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write(" \n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<title>Lyric~音乐工厂</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/frame.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/music.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/index.css\">\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"image/favicon.ico\" />\n");
      out.write("</head>\n");
      out.write("<body>\t\n");
      out.write("<div class=\"header\">\n");
      out.write("\t<div class=\"header-center center\">\n");
      out.write("\t\t<h1>Lyric 音乐场</h1>\n");
      out.write("\t\t<ul class=\"nav\">\n");
      out.write("\t\t\t<li><a href=\"javascript:;\" class=\"active\">发现音乐</a></li>\n");
      out.write("\t\t\t<li><a href=\"./my\">我的音乐</a></li>\n");
      out.write("\t\t\t<li><a href=\"javascript:;\">热门专辑</a></li>\n");
      out.write("\t\t\t<li><a href=\"javascript:;\">在线好友</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<div class=\"top-tool\">\n");
      out.write("            <div class=\"top-search\">\n");
      out.write("                <i class=\"icn-search\"></i>\n");
      out.write("                <input type=\"text\" placeholder=\"单曲/歌手/专辑/歌单/用户\">\n");
      out.write("                <ul class=\"result\"></ul>\n");
      out.write("            </div>\n");
      out.write("\t\t\t<div class=\"top-user\">\n");
      out.write("                <a href=\"./login\" class=\"user-login\">登录</a>\n");
      out.write("                <div class=\"user-memb\">\n");
      out.write("                    <h4>用户</h4>\n");
      out.write("                    <ul class=\"slide-down\">\n");
      out.write("                        <li><a href=\"./my\">我的主页</a></li>\n");
      out.write("                        <li><a href=\"javascript:;\" class=\"logout\">退出</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div> \n");
      out.write("            </div>\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"sub-list\">\n");
      out.write("\t\t<div class=\"center\">\n");
      out.write("\t\t\t<ul class=\"sub-nav\">\n");
      out.write("\t\t\t\t<li><a class=\"active\" href=\"javascript:;\">推荐</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"javascript:;\">排行榜</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"javascript:;\">歌单</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"javascript:;\">主播电台</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"javascript:;\">歌手</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"javascript:;\">新碟上架</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"wrap\">\n");
      out.write("\t<div class=\"wrap-in\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"cloumn main-top\">\n");
      out.write("            <div class=\"btns\">\n");
      out.write("                <a href=\"javascript:;\" class=\"btn-down\" title=\"客户端下载\">客户端下载</a>\n");
      out.write("                <a href=\"javascript:;\" class=\"btn-reg sm\">注册帐号</a>\n");
      out.write("                <a class=\"tool-border\"></a>\n");
      out.write("                <a href=\"javascript:;\" class=\"btn-browse sm\">站台一览</a>\n");
      out.write("                <a href=\"javascript:;\" class=\"btn-gift sm\">等级礼包</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"slides\">\n");
      out.write("                <ul class=\"points\">\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/player-1.jpg\" alt=\"图片-1\"/></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/player-2.jpg\" alt=\"图片-2\"/></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/player-3.jpg\" alt=\"图片-3\"/></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/player-4.jpg\" alt=\"图片-4\"/></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/player-5.jpg\" alt=\"图片-5\"/></a></li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"sub-tips\">\n");
      out.write("                    <li class=\"active\">●</li><li>●</li><li>●</li><li>●</li><li>●</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"aside\">\n");
      out.write("                <ul class=\"aside-tab\">\n");
      out.write("                    <li><a href=\"javascript:;\" class=\"active\">最新</a></li>\n");
      out.write("                    <li><a href=\"javascript:;\">活动</a></li>\n");
      out.write("                    <li><a href=\"javascript:;\">公告</a></li>\n");
      out.write("                    <li><a href=\"javascript:;\">焦点</a></li>\n");
      out.write("                    <li class=\"tab-tool\">+</li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"aside-list\"></ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"column main-type\">\n");
      out.write("            <div class=\"enter\">\n");
      out.write("                <ul class=\"enter-btns\">\n");
      out.write("                    <li><a href=\"javascript:;\">听歌</a></li>\n");
      out.write("                    <li class=\"border-aside\"></li>\n");
      out.write("                    <li><a href=\"javascript:;\">活动</a></li>\n");
      out.write("                    <li class=\"border\"></li>\n");
      out.write("                    <li><a href=\"javascript:;\">VIP</a></li>\n");
      out.write("                    <li class=\"border-aside\"></li>\n");
      out.write("                    <li><a href=\"javascript:;\">领奖</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"enter-share\">\n");
      out.write("                    <li><a href=\"javascript:;\">官方微信</a></li><li class=\"bdr-aside\">|</li>\n");
      out.write("                    <li><a href=\"javascript:;\">新浪微博</a></li><li class=\"bdr-aside\">|</li>\n");
      out.write("                    <li><a href=\"javascript:;\">YY语音</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"acts\">\n");
      out.write("                <ul class=\"acts-list\">\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/hit-1.jpg\" alt=\"\"></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/hit-2.jpg\" alt=\"\"></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/hit-3.jpg\" alt=\"\"></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/hit-4.jpg\" alt=\"\"></a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"column main-pro\">\n");
      out.write("            <div class=\"section\">\n");
      out.write("                <h3>新碟上架<span>PROMOTION</span></h3>\n");
      out.write("                <ul class=\"pro-list\">\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/view-1.jpg\" alt=\"\"></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/view-2.jpg\" alt=\"\"></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\"><img src=\"image/view-3.jpg\" alt=\"\"></a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"sidebar\"><img src=\"image/wrap.png\" alt=\"\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"column main-hot\">\n");
      out.write("            <div class=\"sidebar\">\n");
      out.write("                <h3><i class=\"icon\"></i>歌曲分类</h3>\n");
      out.write("                <ul class=\"hot-tab\">\n");
      out.write("                    <li><a href=\"javascript:;\">华语 - 流行<i></i></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\">轻音 - 弹奏<i></i></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\">摇滚 - 电子<i></i></a></li>\n");
      out.write("                    <li><a href=\"javascript:;\">古典 - 民谣</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <a href=\"javascript:;\" class=\"hot-load\">所有分类&gt;</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"section\">\n");
      out.write("                <h3>热门歌单<span>PLAYLIST</span></h3>\n");
      out.write("                <ul class=\"hot-list\">\n");
      out.write("                    <li><img src=\"image/player-2.jpg\" alt=\"\"></li>\n");
      out.write("                    <li><img src=\"image/player-3.jpg\" alt=\"\"></li>\n");
      out.write("                    <li><img src=\"image/player-4.jpg\" alt=\"\"></li>\n");
      out.write("                    <li><img src=\"image/player-5.jpg\" alt=\"\"></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"column main-rank\">\n");
      out.write("            <div class=\"section\">\n");
      out.write("                <h3>排行榜<span>RANKLIST</span></h3>\n");
      out.write("                <div class=\"rank\">\n");
      out.write("                    <dl class=\"rank-blk\">\n");
      out.write("                        <dt class=\"top\">\n");
      out.write("                            <a href=\"javascript:;\" class=\"dt-img\"><img src=\"image/musicUp.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"dt-txt\">\n");
      out.write("                                <a href=\"javascript:;\" class=\"title\">云音乐飙升榜</a>\n");
      out.write("                                <a href=\"javascript:;\" class=\"icon icon-play\"></a>\n");
      out.write("                                <a href=\"javascript:;\" class=\"icon icon-store\" data-type=\"up\"></a>\n");
      out.write("                            </div>\n");
      out.write("                        </dt>\n");
      out.write("                    </dl>\n");
      out.write("                    <div class=\"blk-border\"></div>\n");
      out.write("                    <dl class=\"rank-blk\">\n");
      out.write("                        <dt class=\"top\">\n");
      out.write("                            <a href=\"javascript:;\" class=\"dt-img\"><img src=\"image/musicNew.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"dt-txt\">\n");
      out.write("                                <a href=\"javascript:;\" class=\"title\">云音乐新歌榜</a>\n");
      out.write("                                <a href=\"javascript:;\" class=\"icon icon-play\"></a>\n");
      out.write("                                <a href=\"javascript:;\" class=\"icon icon-store\" data-type=\"new\"></a>\n");
      out.write("                            </div>\n");
      out.write("                        </dt>\n");
      out.write("                    </dl>\n");
      out.write("                    <div class=\"blk-border\"></div>\n");
      out.write("                    <dl class=\"rank-blk\">\n");
      out.write("                        <dt class=\"top\">\n");
      out.write("                            <a href=\"javascript:;\" class=\"dt-img\"><img src=\"image/musicCreate.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"dt-txt\">\n");
      out.write("                                <a href=\"javascript:;\" class=\"title\">原创歌曲榜</a>\n");
      out.write("                                <a href=\"javascript:;\" class=\"icon icon-play\"></a>\n");
      out.write("                                <a href=\"javascript:;\" class=\"icon icon-store\" data-type=\"create\"></a>\n");
      out.write("                            </div>\n");
      out.write("                        </dt>\n");
      out.write("                    </dl>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"sidebar\">\n");
      out.write("                <h3>听友评论</h3>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"footer\">\n");
      out.write("    <div class=\"footer-center\">\n");
      out.write("        <a class=\"recruit\" href=\"javascript:;\">\n");
      out.write("            <p>独立音乐人招募计划</p>\n");
      out.write("            <span>加入我们 即将与超过亿万乐迷互动</span>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"copy\">\n");
      out.write("            <ul class=\"copy-list\">\n");
      out.write("                <li><a href=\"javascript:;\">关于本站</a></li><li>-</li>\n");
      out.write("                <li><a href=\"javascript:;\"> 客户服务</a></li><li>-</li>\n");
      out.write("                <li><a href=\"javascript:;\"> 服务条款</a></li><li>-</li>\n");
      out.write("                <li><a href=\"javascript:;\"> 网站导航</a></li>\n");
      out.write("                <span>Lyric旗下版权所有©1997-2015 </span>\n");
      out.write("            </ul>\n");
      out.write("            <p>网络文化经营许可证：粤网文[2014]0332-034号</p>\n");
      out.write("        </div>\n");
      out.write("        <a class=\"feedback\" href=\"javascript:;\"><i></i>意见反馈</a> \n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 播放条 -->\n");
      out.write("<div class=\"fix-bottom\">\n");
      out.write("    <div class=\"fix-lock\">\n");
      out.write("        <div class=\"lock-img\"><a href=\"javascript:;\" class=\"unlock\"></a></div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"fix-play\">\n");
      out.write("        <div class=\"play-btns\" id=\"play-btns\">\n");
      out.write("            <a href=\"javascript:;\" class=\"prv\" title=\"上一首\"></a>\n");
      out.write("            <a href=\"javascript:;\" id=\"data-ps\" class=\"ply\" title=\"播放\"><!--.pas--></a>\n");
      out.write("            <a href=\"javascript:;\" class=\"nxt\" title=\"下一首\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"play-head\">\n");
      out.write("            <a href=\"#\"><img src=\"image/default_album.jpg\" alt=\"\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"play-ing\" id=\"play-ing\">\n");
      out.write("            <div class=\"ptitle\">\n");
      out.write("                <a href=\"#\" class=\"title\" title=\"曲名\"></a>\n");
      out.write("                <a href=\"#\" class=\"singer\" title=\"演绎者\"></a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"pbar\">\n");
      out.write("                <div class=\"barbg\"><!-- 总进度条 -->\n");
      out.write("                    <div class=\"rdy\"></div><!-- 已加载 -->\n");
      out.write("                    <div class=\"cur\">\n");
      out.write("                        <div class=\"cur-inner\">\n");
      out.write("                            <span class=\"btn-cur\"><i></i></span>\n");
      out.write("                        </div>'\n");
      out.write("                        <!-- <span class=\"btn-cur\" id=\"data-cur\"><i><!-- loading... --></i></span> -->\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <span class=\"clock\"><i>00:00</i> / <em>00:00</em></span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"play-oper\" id=\"play-oper\">\n");
      out.write("            <a href=\"javascript:;\" class=\"icon-colle\" title=\"收藏\"></a>\n");
      out.write("            <a href=\"javascript:;\" class=\"icon-share\" title=\"分享\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"play-form\">\n");
      out.write("            <div class=\"form-title\">\n");
      out.write("                <h3>播放列表</h3>\n");
      out.write("                <a href=\"javascript:;\" class=\"icon-colle\"><span></span>收藏全部</a>\n");
      out.write("                <span>|</span>\n");
      out.write("                <a href=\"javascript:;\" class=\"icon-empty\"><span></span>清空</a>\n");
      out.write("                <a href=\"javascript:;\" class=\"table-close\" title=\"关闭\"></a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-tab\" id=\"form-tab\">\n");
      out.write("                <ul class=\"mtab\" id=\"mtab\"><!-- 播放列表 --></ul>    \n");
      out.write("                <div class=\"empty\">播放列表为空哦</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"scrol\"><span class=\"icon-scl\"></span></div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"play-ctrl\" id=\"play-ctrl\">\n");
      out.write("            <div class=\"cbar\">  \n");
      out.write("                <div class=\"barbg\"><!-- 音量调节条 -->\n");
      out.write("                    <div class=\"cur\">\n");
      out.write("                        <span class=\"btn-cur\" id=\"ctrl-cur\"></span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>        \n");
      out.write("            <a href=\"javascript:;\" class=\"icon-vol\" title=\"音量\"></a>\n");
      out.write("            <a href=\"javascript:;\" class=\"icon-loop\" id=\"data-lop\" title=\"循环\"></a>\n");
      out.write("            <div class=\"lp-tip\">单曲循环</div>\n");
      out.write("            <span class=\"music-list\">\n");
      out.write("                <a href=\"javascript:;\" class=\"icon-list\" title=\"播放列表\">0</a>\n");
      out.write("                <em>已添加到播放列表</em>\n");
      out.write("            </span>\n");
      out.write("        </div>\n");
      out.write("       \n");
      out.write("    </div>\n");
      out.write("    <audio id=\"player\" controls=\"false\">\n");
      out.write("        <source src=\"\"></source>\n");
      out.write("        <embed src=\"\" type=\"\" controls=\"false\">\n");
      out.write("    </audio>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../../../sea-modules/seajs/sea.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    \n");
      out.write("    //设置configuration\n");
      out.write("    seajs.config({\n");
      out.write("        base: \"../../../sea-modules\",\n");
      out.write("        alias: {\n");
      out.write("            \"jquery\" : \"jquery/jquery.js\"\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    //引入main.js\n");
      out.write("    seajs.use('js/index/main');\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
